[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
revvek_capstone = "HCxL9BAMFjfMqfboyYSzuxo7baShezELbyfvRZjgEVvP"

[programs.localnet]
revvek_capstone = "HCxL9BAMFjfMqfboyYSzuxo7baShezELbyfvRZjgEVvP"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
