export type CarListing = {
  make: string;
  model: string;
  year: number;
  type: string;
  sellerGovtID: string;
  mileage: number;
  fuelType: string;
  transmission: string;
  condition: string;
  color: string;
  engineSize: string;
  accidentHistory: string;
  serviceRecords: string;
  insuranceDetails: string;
  location: string;
  price: number;
  negotiable: boolean;
  photos: string[];
  video: File;
  sellerName: string;
  contact: string;
  reasonForSale?: string;
  vin?: string;
  warranty?: string;
};
